# Generated by Django 5.1.3 on 2024-11-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tel',
            field=models.CharField(default='010-0000-0000', max_length=50),
        ),
    ]
